package vmc

type AutoGenerated struct {
	AwsAccountNumber string `json:"aws_account_number"`
	OrgID            string `json:"org_id"`
	Reason           string `json:"reason"`
	Region           string `json:"region"`
	RequestDetails   struct {
		Key struct {
			AwsQuotaRequestID    string `json:"aws_quota_request_id"`
			AwsSupportCaseID     string `json:"aws_support_case_id"`
			AwsSupportCaseStatus string `json:"aws_support_case_status"`
			DesiredValue         int    `json:"desired_value"`
			DetailStatus         string `json:"detail_status"`
			ResolvedAt           string `json:"resolved_at"`
		} `json:"key"`
	} `json:"request_details"`
	RequestStatus  string `json:"request_status"`
	RequesterEmail string `json:"requester_email"`
	TaskID         string `json:"task_id"`
}

type ServiceQuotaRequest struct {
	Created           string                   `json:"created"`
	Id                string                   `json:"id"`
	Updated           string                   `json:"updated"`
	UpdatedByUserId   string                   `json:"updated_by_user_id"`
	UserId            string                   `json:"user_id"`
	UserName          string                   `json:"user_name"`
	Version           string                   `json:"version"`
	UpdatedByUserName string                   `json:"updated_by_user_name"`
	AwsAccountNumber  string                   `json:"aws_account_number"`
	OrgId             string                   `json:"org_id"`
	Reason            string                   `json:"reason"`
	Region            string                   `json:"region"`
	RequestDetails    map[string]RequestDetail `json:"request_details"`
	RequestStatus     string                   `json:"request_status"`
	RequesterEmail    string                   `json:"requester_email"`
	TaskId            string                   `json:"task_id"`
}

type ServiceQuotaRequests []ServiceQuotaRequest

type RequestDetail struct {
	AwsQuotaRequestId    string `json:"aws_quota_requet_id"`
	AwsSupportCaseId     string `json:"aws_support_case_id"`
	AwsSupportCaseStatus string `json:"aws_support_case_status"`
	DesiredValue         string `json:"desired_value"`
	DetailStatus         string `json:"detail_status"`
	ResolvedAt           string `json:"resolved_at"`
}

type AccountLink map[string]string

type AwsCompatibleSubnets struct {
	CustomerAvailableZones []string `json:"customer_available_zones"`
	VpcMap                 map[string]VpcInfoSubnets
}

type VpcInfoSubnets struct {
	CidrBlock   string       `json:"cidr_block"`
	Description string       `json:"description"`
	Subnets     []SubnetInfo `json:"subnet"`
	VpcId       string       `json:"vpc_id"`
}

type SubnetInfo struct {
	AvailabilityZone   string `json:"availability_zone"`
	AvailabilityZoneId string `json:"availability_zone_id"`
	Compatible         bool   `json:"compatible"`
	ConnectedAccountId string `json:"connected_account_id"`
	Name               string `json:"name"`
	Note               string `json:"note"`
	RegionName         string `json:"region_name"`
	SubnetCidrBlock    string `json:"subnet_cidr_block"`
	SubnetId           string `json:"subnet_id"`
	VpcCidrBlock       string `json:"vpc_cidr_block"`
	VpcId              string `json:"vpc_id"`
}

type AwsCustomerConnectedAccount struct {
	Created                 string                       `json:"created"`
	Id                      string                       `json:"id"`
	Updated                 string                       `json:"updated"`
	UpdatedByUserId         string                       `json:"updated_by_user_id"`
	UserId                  string                       `json:"user_id"`
	UserName                string                       `json:"user_name"`
	Version                 int32                        `json:"version"`
	UpdatedByUserName       string                       `json:"updated_by_user_name"`
	AccountNumber           string                       `json:"account_number"`
	CfStackName             string                       `json:"cf_stack_name"`
	OrgId                   string                       `json:"org_id"`
	PolicyExternalId        string                       `json:"policy_external_id"`
	PolicyPayerArn          string                       `json:"policy_payer_arn"`
	PolicyPayerLinkedArn    string                       `json:"policy_payer_linked_arn"`
	PolicyServiceArn        string                       `json:"policy_service_arn"`
	RegionToAzShadowMapping map[string]map[string]string `json:"region_to_az_to_shadow_mapping"`
	State                   string                       `json:"state"`
}

type AwsCustomerConnectedAccounts []AwsCustomerConnectedAccount

type AwsSddcConnection struct {
	Created                string            `json:"created"`
	Id                     string            `json:"id"`
	Updated                string            `json:"updated"`
	UpdatedByUserId        string            `json:"updated_by_user_id"`
	UserId                 string            `json:"user_id"`
	UserName               string            `json:"user_name"`
	Version                int               `json:"version"`
	UpdatedByUserName      string            `json:"updated_by_user_name"`
	CgwPresent             bool              `json:"cgw_present"`
	CidrBlockSubnet        string            `json:"cidr_block_subnet"`
	CidrBlockVpc           string            `json:"cidr_block_vpc"`
	ConnectedAccountId     string            `json:"connected_account_id"`
	ConnectionOrder        int               `json:"connection_order"`
	CustomerEniInfos       []CustomerEniInfo `json:"customer_eni_infos"`
	DefaultRouteTable      string            `json:"default_route_table"`
	EniGroup               string            `json:"eni_group"`
	OrgId                  string            `json:"org_id"`
	SddcId                 string            `json:"sddc_id"`
	State                  string            `json:"state"`
	SubnetAvailabilityZone string            `json:"subnet_availability_zone"`
	SubnetId               string            `json:"subnet_id"`
	VpcId                  string            `json:"vpc_id"`
}

type CustomerEniInfo struct {
	EniId              string   `json:"eni_id"`
	PrimaryIpAddress   string   `json:"primary_ip_address"`
	SecondaryIpAddress []string `json:"secondary_ip_addresses"`
}

type AwsSddcConnections []AwsSddcConnection
